### ISSUE TITLE
excess code in Buffer.prototype.compare

### ISSUE THREAD

**Issue by fanatid** [feross/buffer#110]
https://github.com/feross/buffer/blob/efda3143011d6befa0771f4850351158d4b89bb2/index.js#L457

I don't understand why you checks that `b` is `Buffer` instance or that `b` equal to `this`. You do this in [Buffer.compare](https://github.com/feross/buffer/blob/efda3143011d6befa0771f4850351158d4b89bb2/index.js#L278)

**Comment by feross** [comment]
Technically the error message is slightly different (not plural) for `Buffer.prototype.compare`. But you're right about checking if the two buffers are the same. Will fix.
