### ISSUE TITLE
allocUnsafe/alloc/from

### ISSUE THREAD

**Issue by fanatid** [feross/buffer#111]
Any plans about supporting new static functions? Ref: https://github.com/nodejs/node/pull/4682/

**Comment by feross** [comment]
Buffer was actually quite a bit behind the node.js buffer version on `master`. I just spent a few hours updating it to match the latest stuff. Still trying to get all the tests to pass.

**Comment by feross** [comment]
So, this took way longer that I expected. Worked on it all day today too. The node.js buffer test suite has improved quite a bit, so there were a lot of bugs to fix!

PR incoming in a minute.

**Comment by feross** [comment]
Released as 4.6.0.
