### ISSUE TITLE
Add missing .lastIndexOf method

### ISSUE THREAD

**Issue by feross** [feross/buffer#114]
Node.js documentation for .lastIndexOf: https://nodejs.org/api/buffer.html#buffer_buf_lastindexof_value_byteoffset_encoding

> Identical to Buffer#indexOf(), but searches the Buffer from back to front instead of front to back. Returns the starting index position of value in Buffer or -1 if the Buffer does not contain value. The value can be a String, Buffer or Number. Strings are by default interpreted as UTF8. If byteOffset is provided, will return the last match that begins at or before byteOffset.

@dcposch's PR: https://github.com/nodejs/node/pull/4846

**Comment by feross** [comment]
@dcposch -- any interest in sending a PR to implement this? ;)

**Comment by dcposch** [comment]
lol k

**Comment by feross** [comment]
Yo @dcposch, no pressure, but this issue is still open if you want it 😉

**Comment by dcposch** [comment]
sure, on it

**Comment by feross** [comment]
Awesome! Fixed by #127
