### ISSUE TITLE
Call correct set method on Buffer.copy()

### ISSUE THREAD

**Issue by felix** [feross/buffer#118]
This is only for v3.6.0 which is still the latest pulled in by current stable webpack (v1.13.0) via node-libs-browser. See PR #117.
An alternative is for node-libs-browser to update their dependency, see webpack/node-libs-browser#39.

**Comment by feross** [comment]
I feel your pain, but I don't want to maintain two branches, a v3 and v4, just because webpack hasn't updated their dependencies. I already barely have time to maintain all my packages -- hope you understand!

There are many other bugfixes for correctness in v4, so they really should update.

**Comment by felix** [comment]
I understand. /me sighs
