### ISSUE TITLE
TODO: Isolate test fixtures

### ISSUE THREAD

**Issue by dcousens** [feross/buffer#119]
Tests like: https://github.com/feross/buffer/blob/master/test/to-string.js

Could simply be 1 function iterating over an array of:

``` javascript
{
  'source': 'Ձאab',
  'source-encoding': 'utf8',
  'target': '1YHXkGFi',
  'target-encoding': 'base64'
}
```

Even if it is in the same file...  makes test extraction/addition/refactoring *sooo* much easier.

**Comment by feross** [comment]
Meh, not a fan.

When a test fails, this would make it harder to tell exactly which case the test failed on.

I prefer verbose tests, and I use 'Find and Replace' regexes when I need to do massive refactoring (which is not that often).

Matter of taste, I guess.

**Comment by dcousens** [comment]
@feross it does make using external test fixtures quite a bit more difficult?

My motivation for this was that I was intending to bring in some more UTF-8 test fixtures as well as use the existing ones in an external project.

Remembering tests can be isolated using their description,  which could be a combination of the test data that makes them unique and easily isolated,  negating:

> When a test fails, this would make it harder to tell exactly which case the test failed on.

**Comment by feross** [comment]
@dcousens Can you send a PR to demonstrate what such a change might look like?
