### ISSUE TITLE
Buffer.from not converting to string when built with webpack

### ISSUE THREAD

**Issue by marr** [feross/buffer#124]
Hi,
Thanks for this library, I am excited to use it for some base64 encoding. 

I illustrated an error I found here https://github.com/marr/buffer-shim

Basically, running `npm test` fails due to something with Buffer not being shimmed properly with webpack.

In node, when I execute: `Buffer.from('foo').toString('base64')` the output is `Zm9v`.
In a webpack bundled version, that code returns `AAAA`. 

Note that I was using Chrome 51 to reproduce the breaking behavior. 
Run `npm build` and Open index.html to see the browser fail, or just run `npm test` to see it fail in a terminal.

webpack v1.13.1
chrome osx Version 51.0.2704.106 (64-bit)

**Comment by dcousens** [comment]
Could you provide details that might allow us to look into this without investigating your library line-by-line?

**Comment by marr** [comment]
@dcousens My library is only three lines:

```
const assert = require('assert')

const foo = Buffer.from('foo').toString('base64')

assert.equal(foo, 'Zm9v', '"foo" is base64 encoded correctly')
```

When I use that in pure node, it passes. When I webpack that file, which imports the buffer lib, I see the output from `Buffer.from('foo').toString('base64')` equal to `AAAA`.

**Comment by feross** [comment]
The version of `webpack` that you're using is giving you an old (3.x) version of `buffer`.

You can confirm this by running `npm ls buffer` and checking the version that shows up. The latest version is 4.7.1.

You can file an issue with `webpack`, or it looks like you can install the latest beta of webpack (2.x). `npm install webpack@beta --save`
