### ISSUE TITLE
Firefox 48 subarray returns the wrong thing

### ISSUE THREAD

**Issue by amasad** [feross/buffer#131]
Firefox 48 includes a regression in Uint8Array.prototype.subarray which makes it return the full array instead of the subarray. We can probably catch it in `typedArraySupport`

```js
var Buffer = require("buffer").Buffer
var b = new Buffer(100)
document.write(b.subarray(50, 100).length); // expected: 50, actual: 100
```

[On RequireBin](http://requirebin.com/?gist=2405f809be7771109ce0ac172804bc1b)

**Comment by amasad** [comment]
I'm curious why is Firefox the only browser not in the saucelabs tests?

**Comment by kkHAIKE** [comment]
may be new version fix it
https://github.com/feross/buffer/pull/97

**Comment by rubensayshi** [comment]
seems to be fixed with updated browserify

**Comment by amasad** [comment]
Oh ok, the folks at Mozilla also mentioned it's fixed with the new browserify. Now the problem is with webpack 1.x

**Comment by feross** [comment]
@amasad Glad you got this figured out. Btw, Firefox is tested, but the badge was having some issues updating recently.
