### ISSUE TITLE
UTF8 decoding differs from Node

### ISSUE THREAD

**Issue by dcousens** [feross/buffer#133]
### Code
``` js
var salt = 'mnemonicメートルガバヴァぱばぐゞちぢ十人十色'
var buffer = new Buffer(salt, 'utf8')

console.log(buffer.toString('base64'))
```

### Results

**node v6.5.0**
``` js
bW5lbW9uaWPjg6Hjg7zjg4jjg6vjgqvjgpnjg4/jgpnjgqbjgpnjgqHjga/jgprjga/jgpnjgY/jgpnjgp3jgpnjgaHjgaHjgpnljYHkurrljYHoibI=
```

**Chromium 53.0.2785.101**
``` js
bW5lbW9uaWPDo8aSwqHDo8aSwrzDo8aSy4bDo8aSwqvDo+KAmsKrw6PigJrihKLDo8aSwo/Do+KAmuKEosOj4oCawqbDo+KAmuKEosOj4oCawqHDo8KBwq/Do+KAmsWhw6PCgcKvw6PigJrihKLDo8KBwo/Do+KAmuKEosOj4oCawp3Do+KAmuKEosOjwoHCocOjwoHCocOj4oCa4oSiw6XCjcKBw6TCusK6w6XCjcKBw6jigLDCsg==
```

**Comment by jessetane** [comment]
@dcousens is your document's character encoding set to utf-8?

`<meta charset=utf-8>`

**Comment by dcousens** [comment]
@jessetane nailed it.

How do we help make that obvious... can we perhaps inform users?

**Comment by jessetane** [comment]
Interesting idea, something like `if ('ト'.length !== 1) throw new Error('encoding error')`?

**Comment by dcousens** [comment]
When the effect is so subtle,  I think such an error would be greatly appreciated by most users.

**Comment by jessetane** [comment]
For what it's worth it looks like Firefox actually already does warn if your document's encoding is unspecified.

**Comment by feross** [comment]
Wow, I had no idea that the html document encoding could affect javascript strings! I guess that's just because I always use a utf8 document encoding.

**Comment by feross** [comment]
Sent a PR to fix this: https://github.com/feross/buffer/pull/134

**Comment by jessetane** [comment]
Just to be precise about why this happened: the browser can only guess what encoding a source file is in unless you specify it via meta tag or http header. Of course everyone stores text files as utf-8 these days, but for backward compatibility the browser probably assumed iso-8859-1 and so OP just experienced this mismatch.

**Comment by feross** [comment]
@jessetane Thanks for the explanation. Lmk if you you think the wording could be improved in the PR.

**Comment by feross** [comment]
Closing, see PR for explanantion.
