### ISSUE TITLE
Standalone version server error 503

### ISSUE THREAD

**Issue by dragonnn** [feross/buffer#144]
I want to user the standalone version but the page is broken :/. Can you fix that or upload it somewhere other? 
https://wzrd.in/standalone/buffer

**Comment by feross** [comment]
I just notified @maxogden that `wzrd.in` is down. Should be resolved shortly.

In the meantime, you can generate your own standalone version by git cloning this repo and running:

```
cd buffer
npm install
browserify -s Buffer -r ./ | uglifyjs -m > buffer.min.js
```

**Comment by AbhinaiRaj** [comment]
Me to its not working gateway time out. Can any one share the buffer.js file or a solution. Thanks In Advance.

**Comment by feross** [comment]
There's a working standalone version hosted here: https://bundle.run/buffer
