### ISSUE TITLE
length property not available

### ISSUE THREAD

**Issue by candeira** [feross/buffer#145]
How to find the length of a Buffer instance? 
```
b = buffer.Buffer([65, 66, 67])
[]
b.length
undefined
b[0]
65
b[1]
66
b[2]
67
b[3]
undefined
```

**Comment by feross** [comment]
What environment are you running in? I can't imagine this isn't working correctly. I'll reopen once/if this is confirmed as a bug.

**Comment by dcousens** [comment]
Hey Javier :smiley: ,
Can you provide more contextual information?
That certainly doesn't look right.

**Comment by candeira** [comment]
Yeah, I'm doing weird things with the library, running it after vendoring it into an OS project I'm working on (https://github.com/pybee/batavia.git), and I'd broken the module. In my discharge, I'm a Python programmer writing JS... but I apologise for making an issue out of some half-baked misunderstanding.

I'm having a different issue now, I don't know whether because of something I've done or because of some incompatibility between Chrome  48.0.2564.116 (64-bit) and the Buffer library. Apologies if this is not the place to ask, maybe you can point me somewhere else.

Here's what the error says: 

```
Uncaught TypeError: Cannot assign to read only property 'from' of function 'function Buffer(arg, encodingOrOffset, length) {
```

And the error is in this line:

```
    Buffer.from = function (value, encodingOrOffset, length) {
        return from(value, encodingOrOffset, length)
    }
```

**Comment by dcousens** [comment]
@candeira are you using browserify? I feel like this could related to the weird way you've bundled it.

**Comment by candeira** [comment]
We're not using browserify nor other toolchains, yet. We're bundling it by folding it in by hand, like cavepeople, until we can figure out how it should be done.

**Comment by dcousens** [comment]
``` javascript
npm install browserify
```

`vendor.js`
``` javascript
module.exports = {
  Buffer: require('buffer')
}
```

``` bash
$ browserify vendor.js --standalone boop > app.js
```

You will now be able to use <script src="app.js" /> in your browser, with each of the above exports accessible via the global `boop` object (or whatever you chose for the --standalone parameter above).

**Comment by candeira** [comment]
Thanks, dcousens. I'll give it a go integrating it with the rest of the mess we've built, which includes a lot of non-npm JS modules in namespaces, and let you know how I go.

I'd also happily shout you drinks/dinner and show you what we have so far, if you have a free hour to spare some time in the next couple of weeks.

**Comment by feross** [comment]
Even simpler:

```
$ npm install browserify
$ browserify --standalone buffer --require buffer > buffer.js
```

Then use buffer.js and you'll have a `buffer` global. The Buffer constructor is on `buffer.Buffer`.

**Comment by candeira** [comment]
Thanks feross as well. Right now batavia concatenates all JS with a simple Makefile, and we just make sure we namespace everything. It might make sense for us to write our code as JS modules and have browserify bundle up everything, so we can keep using our namespaces. I'll try and figure it out.

It's all a learning curve. I'm now glad I opened this (blatantly wrong) issue, and I appreciate the kind advice.

**Comment by candeira** [comment]
Thanks feross and dcousens. I have browserify vendoring batavia's external dependencies, and it's now integrated with batavia's troglodyte make/cat JS bundler. Much appreciated.

**Comment by dcousens** [comment]
And working too?

**Comment by candeira** [comment]
All working now too, with new hotness thanks to yarn. My problem was mostly ignorance of the platofrm, growing pains. Thanks again.
