### ISSUE TITLE
use of console.error is causing errors downstream

### ISSUE THREAD

**Issue by Lyrencropt** [feross/buffer#152]
I'm not certain if this qualifies as a "bug" in the usual sense, but we have a bundle that sometimes runs in a very old environment (IE 5). Buffer is included as part of this bundle, but doesn't run -- that is fine, because we don't actually use it when we're in this environment. However, the recent update it is causing it to break simply by including it, due to console being undefined.

I have seen many other projects do like if (console && console.error) {//throw error here} in order to prevent this. Would it be possible for buffer to do this as well? Thanks.

**Comment by feross** [comment]
@Lyrencropt Yes, this is totally reasonable. Done in 5.0.3.
