### ISSUE TITLE
Converting between Buffer and browser built-in types?

### ISSUE THREAD

**Issue by srsudar** [feross/buffer#157]
I appreciate the parity with node's Buffer API. However, some of the browser APIs I'm working with expect things like `ArrayBuffer` and `Blob`. I would love a section in the readme talking about the preferred way to convert both to and from `Buffer` and these objects. Linking to your [blob-to-buffer](https://github.com/feross/blob-to-buffer) library would be great, eg, or a pointer to what to do now that `toArrayBuffer()` has been removed from the API.

I've found workarounds, but I'd love to see preferred solutions in one place for easy reference.

**Comment by feross** [comment]
Sure thing, just sent a PR with recommended conversion methods: https://github.com/feross/buffer/pull/158
