### ISSUE TITLE
5.0.6 release issue in node 5/6

### ISSUE THREAD

**Issue by epoberezkin** [feross/buffer#160]
It seems to me that 5.0.6 release causes this issue in [Ajv](https://github.com/epoberezkin/ajv) (via browserify):
https://travis-ci.org/epoberezkin/ajv/builds/219160223

Nothing else has changed in the dependencies.
I will investigate.

**Comment by epoberezkin** [comment]
Specifically this commit breaks it: https://github.com/feross/buffer/commit/24d98b901d826ddb8de43389c494a8dd91fd99bc

**Comment by epoberezkin** [comment]
Specifically, [line 256](https://github.com/feross/buffer/commit/24d98b901d826ddb8de43389c494a8dd91fd99bc#diff-168726dbe96b3ce427e7fedce31bb0bcL256), but only when browserified bundle of [nodent](https://github.com/MatAtBread/nodent) package is uglified.

**Comment by epoberezkin** [comment]
Also, if I insert `if (obj === undefined) throw new Error;` after the line 254 everything works (uglified).

But if I insert `if (obj === undefined) throw new TypeError;` instead, it fails...

**Comment by feross** [comment]
@epoberezkin Thanks for reporting the issue. The commit you linked (https://github.com/feross/buffer/commit/24d98b901d826ddb8de43389c494a8dd91fd99bc) was essentially reverted with this commit (https://github.com/feross/buffer/commit/32e7af9ba9db3abf5f064ea21da8b1336cdf934f) before 5.0.6 was released, so it doesn't seem like it could be the one causing the issue.

**Comment by epoberezkin** [comment]
@feross thank you for looking into it. It's not that I am afraid. All commits starting from https://github.com/feross/buffer/commit/24d98b901d826ddb8de43389c494a8dd91fd99bc until v5.0.6 fail for me.

And even if I revert https://github.com/feross/buffer/commit/c265a5491532e9f94d08849d6fa70df69c4cdaef it still fails.

The last commit that passes is 2ac965b

To summarize, I do the following:
1. generate the bundle of nodent package using browserify in node 6 (if I use 0.10, 0.12 or 4 - it's all ok, if I use 5/6/7 - it fails) 
2. uglify the bundle (if I don't uglify - it's all ok)
3. run karma test of Ajv that loads nodent.min.js as a separate file

The exception is thrown when I `require('nodent')` - I assume that somehow nodent fails to get exported to browserify's require because of the change in buffer, but I didn't manage to isolate the change that does it... I will try again starting from v5.0.6 this time.

It's very consistent, the same  error happens in both Chrome and in PhantomJS.

@matAtHome - maybe you have some idea what can be happening?

**Comment by MatAtBread** [comment]
Can you provide me with a simple Uglify CLI or test case i can examine? Which nodent revision seems to fail?

**Comment by epoberezkin** [comment]
@feross Ok, I think I am beginning to understand...

In v5.0.5 and in 2ac965b in the lines [633](https://github.com/feross/buffer/blob/v5.0.5/index.js#L633) and [764](https://github.com/feross/buffer/blob/v5.0.5/index.js#L764) this package uses global isNaN and not locally defined isnan.

isNaN is different from Number.isNaN and from shim that does `x !== x` - isNaN coerces it's argument to number first, so, for example, `isNaN()` equals to `true` because undefined is coerced to NaN, while `Number.isNaN()` is false.

See https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/isNaN#Confusing_special-case_behavior

**Comment by feross** [comment]
I don't use nodent or know what it is. Here is a full list of the changes to `buffer` between v5.0.5 and v5.0.6. https://github.com/feross/buffer/compare/v5.0.5...master#diff-168726dbe96b3ce427e7fedce31bb0bc

@epoberezkin I don't see what in this set of changes could cause your issue, but happy to take a look if you can show a minimal test case, or if you send a PR to fix the issue.

**Comment by epoberezkin** [comment]
Also `isNaN('foo')` is `true`, `Number.isNaN('foo')` is false.

**Comment by feross** [comment]
Btw, I just noticed that the individual commit you linked (https://github.com/feross/buffer/commit/24d98b901d826ddb8de43389c494a8dd91fd99bc) contains a bug where it reorders line 255 and 256, but that gets fixed in a later commit. This looks like an artifact of the way I interactively committed the individual lines.

But all the commits taken together don't move that line around.

**Comment by feross** [comment]
> @epoberezkin Also `isNaN('foo')` is `true`, `Number.isNaN('foo')` is false.

We're not using `Number.isNaN` in 5.0.6. That was removed in a later commit before 5.0.6 was released.

Also, we never pass a non-string value into the replacement `numberIsNaN` function, so this difference does not matter.

**Comment by epoberezkin** [comment]
see my last 2 comments above - the issue seems to be caused by the difference between `isNaN` (that does coercion) and `isnan` shim that does not. This difference was removed from 5.0.6.

**Comment by epoberezkin** [comment]
> We're not using Number.isNaN in 5.0.6.

I understand it. But the shim you use behaves exactly as Number.isNaN - it does not do coercion. Global isNaN that yo used in 5.0.5 does coercion.

**Comment by feross** [comment]
We never pass a non-string value into `numberIsNaN`, so the difference between the two implementations does not matter.

If you have a test case that shows otherwise, please provide it.

**Comment by epoberezkin** [comment]
Apparently something does... If you pass undefined the result is also different. isNaN() === true and isnan() === false.

**Comment by feross** [comment]
Sorry, I meant we never pass a **non-number** value into `numberIsNaN`.

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. If you have a test case that shows the issue, I'm happy to re-open this.

**Comment by epoberezkin** [comment]
> we never pass a non-number value into numberIsNaN.

Not sure I understand. This `buffer` package is inserted by browserify in ALL packages that use node.js `buffer`, so somehow non-number is passed. If non-number was never passed, it would not have behaved in a different way when I replace isNaN with isnan.

I will try to create a smaller test case.

In any case 5.0.5 -> 5.0.6 seems to be a breaking change and there is nothing I can do to fix the version because it is not a direct dependency...

**Comment by epoberezkin** [comment]
So I'd really appreciate if you could fix it's version in browserify until we figure out what is going on here...

I can create an issue there if needed.

**Comment by feross** [comment]
You can fix the version of `buffer` that is used in your app like this:

```
$ npm install buffer@5.0.5 --save
$ browserify -r buffer/:buffer main.js > bundle.js
```

**Comment by epoberezkin** [comment]
Thank you, I will try it.
