### ISSUE TITLE
Inconsistent with TextDecoder API

### ISSUE THREAD

**Issue by dfcreative** [feross/buffer#164]
Not sure where does it belong, but `Buffer` stringifies some utf-8 chars differently than [`TextDecoder`](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder/decode):

```js
var uint8 = new Uint8Array([236, 134, 219])

var str1 = new TextDecoder('utf8').decode(uint8) //��

var str2 = Buffer.from(uint8).toString('utf8') //���
```

**Comment by jessetane** [comment]
This module aims for compatibility with node's Buffer rather than TextEncoder/Decoder, but as of version 8, it appears node's behavior with respect to replacement character insertion has changed. I'll start looking into this, if anyone knows off hand what changed in node, please let me know.

**Comment by dfcreative** [comment]
@jessetane another think I spotted is inconsistent with node `Buffer` utf8 replacement cases:

```js
Buffer.from([ 0xC0, 0xB1 ]).toString()
//'��' in browser
//'�' in node
```

I use v8.1.2

**Comment by jessetane** [comment]
I glanced at the changelog for 8 and pulled the new tests, looks like quite few other things may have changed too... anyone out there already been thinking about this update yet?

**Comment by feross** [comment]
@jessetane Nope, I have not looked into the changes. Not sure what exactly changed. If you want to look into it, that would be great

You can pull in the latest node.js tests by running `./bin/download-node-tests.js`. We don't have to make all the new tests pass in one go, but can merge them in selectively until they all pass. That's what I've done in the past.

**Comment by NekR** [comment]
Node's `Buffer` is now backed by the Typed Arrays hence `var str2 = Buffer.from(uint8).toString('utf8')` results in `var str2 = Buffer.from(uint8).toString('utf8') //��`

**Comment by feross** [comment]
Closing this since this package does not have a goal of being consistent with `TextDecoder`
