### ISSUE TITLE
iPhone iOS < 10 missing .reverse

### ISSUE THREAD

**Issue by rubensayshi** [feross/buffer#167]
running on iPhone6 iOS8 and iOS9 simulator fails with reverse being undefined, iOS10 is fine,  
is the lack of iOS < 10 support intentional or could we add a `reverse` polyfill?

(looking at stats for our app we see 2.4% iOS 9.3 and rest is all 10+)

**Comment by feross** [comment]
Sorry -- we can't polyfill this. This is part of the `Uint8Array` API, not part of Buffer. If we started polyfilling every API on `Uint8Array`, this library would get huge. That's out-of-scope for this package as far as I'm concerned. But feel free to include the polyfill separately in your own code.

**Comment by dcousens** [comment]
@feross `Buffer` has `reverse` in Node?

**Comment by dcousens** [comment]
This has caught me out too.

**Comment by rubensayshi** [comment]
Node had `Buffer.reverse`, but it's not documented here: https://nodejs.org/api/buffer.html

**Comment by dcousens** [comment]
@rubensayshi it appears node inherits from `UInt8Array`,  https://github.com/nodejs/node/blob/master/lib/buffer.js#L231,  so as @feross said:

> This is part of the Uint8Array API, not part of Buffer

Frustratingly,  this doesn't really leave us in a fortunate position... I suspect `buffer-reverse` is the only reasonable option to roll-out to ... every repo?

**Comment by rubensayshi** [comment]
"The goal is to provide an API that is 100% identical to node's Buffer API."

To me that sounds like this lib is to ensure any buffer methods available in NodeJS would also be available in browsers..?
