### ISSUE TITLE
Buffer without browserify

### ISSUE THREAD

**Issue by marsielko** [feross/buffer#169]
Hello, can you please reupload standalone bundle for non-browserify users. Link in you have there doesn't work anymore.

**Comment by feross** [comment]
The service that generates the build is temporarily down due to an expired certificate. They will be back eventually. In the meantime, you can run this to create your own bundle:

```
git clone git@github.com:feross/buffer.git
cd buffer
npm install
browserify -s Buffer -e ./ > buffer-bundle.js
```

Now use `buffer-bundle.js` wherever you want.

**Comment by feross** [comment]
We're now using https://bundle.run/buffer as our standalone script URL.

**Comment by S-Cardenas** [comment]
> 

This isn't working @feross

**Comment by gabrielmaldi** [comment]
@S-Cardenas while https://bundle.run/buffer returns 500, https://bundle.run/buffer@6.0.3 does work.
