### ISSUE TITLE
a curious phenomenon about Buffer.from()

### ISSUE THREAD

**Issue by CrazyWr** [feross/buffer#171]
`const FF = Buffer.from([0xFF])`
`const O_2 = Buffer.from([0x00])`
`const O_4 = Buffer.from([O_2, O_2])`
`const O_8 = Buffer.from([O_4, O_4])`
`console.log(O_8.length)  => 2`
`O_8  => 0x0000  not  0x0000 0000 `

but 
`const FF = Buffer.from([0xFF])`
`const O_2 = Buffer.from([0x00])`
`const O_4 = Buffer.from([O_2, O_2])`
`const O_8 = Buffer.from([O_2, O_2, O_2, O_2])`
`console.log(O_8.length)  => 4  `
I handled some data about Bluetooth in react-native app with `buffer` and found this.

`"buffer": "^5.0.7"`

**Comment by feross** [comment]
You put four bytes into the Buffer (`Buffer.from([O_2, O_2, O_2, O_2])`) and the length is 4. This is expected, unless I'm missing something.

**Comment by CrazyWr** [comment]
I kown `Buffer.from([O_2, O_2, O_2, O_2]` length is 4, it's good
I  just want to know why is the lenth of`Buffer.from([O_4, O_4])` 2 not 4
`const O_2 = Buffer.from([0x00])`
`const O_4 = Buffer.from([O_2, O_2])`
`const O_8 = Buffer.from([O_4, O_4])`
`console.log(O_8.length) => 2`
