### ISSUE TITLE
Inconsistent with nodejs

### ISSUE THREAD

**Issue by zyuhel** [feross/buffer#172]
Hello,
i'm using the following buffer

``` js
let b = Buffer.from([
191, 164, 235, 131, 30, 28, 164, 179, 101,
138, 94, 36, 115, 176, 83, 193, 9, 177, 85,
228, 189, 193, 127, 71, 165, 16, 211, 132,
228, 241, 57, 207, 254, 152, 122, 98, 100, 
71, 67, 100, 29, 218, 165, 101, 25, 17, 177,
173, 92, 173, 162, 186, 198, 1, 80, 94, 228, 
165, 124, 171, 78, 49, 145, 158
])
```

and toString('utf8') results are different in NodeJS and in browsers. 

It seems that some characters that some sequence which nodejs replace to U+FFFD are more lengthy than the replaced sequence in browser. so output utf8 string is different

**Comment by banezelenak** [comment]
Hi,

Any updates on this issue?

Since I installed newer version of Chrome (60+) the values for toString('hex') differentiate from those in NodeJS, and it is causing big issues for object serialization/deserialization.

**Comment by dcousens** [comment]
@banezelenak please post your test fixtures and Chrome version for that issue!

**Comment by dcousens** [comment]
@zyuhel can you please post the different results you get and what browsers you used?

**Comment by jessetane** [comment]
this and #164 should likely be merged

**Comment by dcousens** [comment]
Closing in favour of #164,  but @zyuhel and @banezelenak please don't hesitate to add your test fixtures to that issue!

**Comment by jessetane** [comment]
the tests are already in node. to get them just do `./bin/download-node-tests.js`
