### ISSUE TITLE
Consider updating Buffer.concat() to accept Uint8Array instances

### ISSUE THREAD

**Issue by mbloch** [feross/buffer#173]
In v8.0.0, Node's `Buffer.concat()` function started accepting `Uint8Array`s. It would be nice to add this behavior to the shim.

**Comment by dcousens** [comment]
`s/Browser/Buffer`?

**Comment by mbloch** [comment]
Silly me, fixed now.

**Comment by feross** [comment]
This will be released in 5.1.0
