### ISSUE TITLE
Drop Safari 5.1 - 9 support

### ISSUE THREAD

**Issue by feross** [feross/buffer#182]
Let's drop these Safari version which have < 0.1% usage:

5.1 - 0.09%
6.1 - 0.01%
8 - 0.04%
9 - 0.06%

We'll still keep these versions which have > 0.1% usage:

9.1 - 0.24%
10 - 0.16%
10.1 - 0.42%
11 - 1.49%

I don't plan to intentionally break older Safari versions, but I don't think there's enough usage to justify worrying about it, or guaranteeing support.

**Comment by dcousens** [comment]
Can we `throw` in those browsers at least?

**Comment by feross** [comment]
@dcousens What's the advantage of that? Isn't partial support better than being totally broken? Say that 95% of methods work fine (and 100% of the ones that are used in an app), then throwing would make things worse...

Willing to log some output at least, but hopefully the browser detection code won't add too many bytes...

**Comment by feross** [comment]
We also don't currently print any messages in IE6-10, for example, none of which are supported.

**Comment by feross** [comment]
Okay, this is done.

Before we were running Sauce Labs tests on latest Safari only. Now we run them on Safari 9, 10, 11.

For iOS, before we running on latest iOS only. Now we run on 9.3, 10.3, and 11.2.

This is a net win w/ more testing, just updating the readme to not promise support for old Safari back to 5.1 since it's not even possible to test that on Sauce Labs.
