### ISSUE TITLE
Issue on Buffer support for audio recorded from Web API

### ISSUE THREAD

**Issue by Sowgandh1991** [feross/buffer#187]
Hi i am trying to load a buffer from audio recorded from microphone using Web Audio API. The audio recorded is returned as a Float32Array (e.g [-0.000234https://github.com/feross/buffer/issues -0.00034, -0.0056, 1.1000] ). When I try to create a Buffer like (new Buffer( Uint8Array(float32array)), I would be loosing precision right ?. I am converting to a Buffer to pass data to another opus library.

I seem to be getting all zeros when creating buffer instances, could someone help me on this ?

**Comment by feross** [comment]
If you use `Buffer.from` (same as `new Buffer()`), then you're treating each index of the Float32Array as a byte from 0 to 255. If you instead pass in the underlying ArrayBuffer (using `.buffer`), then the Buffer will get the actual raw bytes.

```js
> Buffer.from(f)
<Buffer 00 00 00 01>
> Buffer.from(f.buffer)
<Buffer e6 5d 75 b9 07 42 b2 b9 34 80 b7 bb cd cc 8c 3f>
```
