### ISSUE TITLE
How to config the version of buffer used in browserify?

### ISSUE THREAD

**Issue by XiaoningLiu** [feross/buffer#198]
It's a simple question. When I use browserify, it will load latest version of this module which doesn't support IE10. What I want is to load buffer@4.x.x with browserify. How can I do that?

**Comment by dcousens** [comment]
Explicitly install `buffer@4.x.x`?
Browserify preferentially uses what is in your `node_modules`

**Comment by feross** [comment]
You can also install the version of `browserify` that comes bundled with the version of `buffer` you want.

That's browserify v13.

There are also other workaround discussed in this PR: https://github.com/browserify/browserify/pull/1678
