### ISSUE TITLE
Can I use this awesome library in my React Native project?

### ISSUE THREAD

**Issue by jamessawyer** [feross/buffer#206]
I am wondering how can I add this to my React Native project.Can I import 'Buffer' like this?
```
import Buffer from 'buffer/Buffer'
```
thanks in advance!

**Comment by hmil** [comment]
Yes you can. But import it like this:

```js
import { Buffer } from 'buffer';
```

Also, add this to the very beginning of your index.js if you want node modules to have access to `Buffer`
```js
global.Buffer = Buffer;
```

**Comment by jamessawyer** [comment]
that's clear,thank you @hmil
