### ISSUE TITLE
please create dist folder with compiled js files

### ISSUE THREAD

**Issue by vladyslav2** [feross/buffer#207]
Looks like your website with compiled files are down
It would be awesome if you can just upload compiled files in the dist folder on github

thank you

**Comment by dcousens** [comment]
@vladyslav2 why not use `browserify`?

**Comment by vladyslav2** [comment]
@dcousens lol. Why do you provide compiled link at all, then?
Maybe cause simple I don't it and neither npm on the device where I need this buffer library?

**Comment by dcousens** [comment]
@vladyslav2 because hopefully, hopefully,  that tool meant we didn't need to include the `dist/`.

**Comment by vladyslav2** [comment]
@dcousens It would be nice if you can be more specific. 
I don't see any reasons why you don't want to include `dist/` folder, especially if you already provide a link in your readme file to a server which goes down time to time. 

Having compiled source on github will solve few problems for you:
1. You don't have to keep a server and maintain/support it
2. People will have more reliable content delivery service for your package
