### ISSUE TITLE
type declarations conflict with those from @types/node

### ISSUE THREAD

**Issue by smcatala** [feross/buffer#213]
since [v5.2.0](https://github.com/feross/buffer/commit/056b770c528a1d28913bda62431d644b60083616).
see https://github.com/Microsoft/TypeScript/issues/26086.

> node_modules/@types/node/index.d.ts:995:14 - error TS2484: Export declaration conflicts with exported declaration of 'Buffer'.

**Comment by mhh1422** [comment]
It looks like the commit fixes the problem, when it will be merged?

**Comment by feross** [comment]
Released as 5.2.1
