### ISSUE TITLE
Convert Uint8Array to Buffer

### ISSUE THREAD

**Issue by mafintosh** [feross/buffer#22]
Should we expose the `augment` function somehow to allow for converting an Uint8Array to a Buffer without having to do a copy (which I believe `new Buffer(uint8array)` does now) ?

**Comment by kalmigs** [comment]
> Published buffer 2.1.8 which exposes `Buffer._augment`.
> 
> Published [typedarray-to-buffer](https://github.com/feross/typedarray-to-buffer). Enjoy!

Thanks for this, so it was really this easy to convert to buffer
