### ISSUE TITLE
Standalone Version is unavailable

### ISSUE THREAD

**Issue by joside** [feross/buffer#229]
At least for me. Can you upload it again?

**Comment by marsrobertson** [comment]
https://www.npmjs.com/package/buffer#install

> A standalone bundle is available here, for non-browserify users.

Kind of...

![image](https://user-images.githubusercontent.com/44369284/56758183-eca81980-678d-11e9-9925-754cdebb6e43.png)

**Comment by vweevers** [comment]
[That project](https://github.com/browserify/wzrd.in/) isn't actively maintained, and fixing it is not a matter of uploading something.

You could try [packd](https://github.com/Rich-Harris/packd) instead: https://bundle.run/buffer@5.2.1 .

**Comment by marsrobertson** [comment]
Thanks! Very useful indeed

**Comment by feross** [comment]
Thanks for the link @vweevers. I'll update the link in the readme.
