### ISSUE TITLE
Uncaught SyntaxError: Function statements require a function name

### ISSUE THREAD

**Issue by veerthiara** [feross/buffer#233]
I am getting Uncaught SyntaxError in my React application deployed on Azure, it points to bundle.js Line 55 which in my case is the buffer module

![image](https://user-images.githubusercontent.com/23288822/61067634-098bda80-a3d6-11e9-83e5-d2202e2d1815.png)

**Comment by vweevers** [comment]
That line isn't from `buffer`. Perhaps it's from your bundler or Babel?

**Comment by veerthiara** [comment]
Hi Why is it failing for just this module? Can you suggest ? my webpack is following below 

const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
    entry: ['babel-polyfill', path.resolve(__dirname, 'src', 'index.js')],
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'bundle.js',
        publicPath: '/'
    },
    plugins: [
        new HtmlWebpackPlugin({
            template: path.resolve(__dirname, 'src', 'index.html'),
            favicon: path.resolve(__dirname, 'src', 'favicon.ico')
        })
    ],
    module: {
        rules: [
            {
                test: /\.js$/,
                include: path.resolve(__dirname, 'src'),
                use: [ 'babel-loader' ]
            },
            {
                test: /\.css$/,
                use: [ 'style-loader', 'css-loader' ]
            },
            {
                test: /\.svg$/,
                use: [ 'file-loader' ]
            },
            { test: /\.(png|woff|woff2|eot|ttf|svg)$/, loader: 'url-loader?limit=100000' }
        ]
    },

**Comment by vweevers** [comment]
> Hi Why is it failing for just this module?

It isn't. That line of code doesn't belong to this module and the error is not related, so this isn't the right place to discuss it. I suggest asking FusionCharts for help. Good luck!

**Comment by feross** [comment]
I'm closing this issue since there's no bug to fix here.
