### ISSUE TITLE
Compilation errors from browsers that dont support globals

### ISSUE THREAD

**Issue by jimmykane** [feross/buffer#235]
Hi 

this piece of code: 

```
Buffer.TYPED_ARRAY_SUPPORT = global.TYPED_ARRAY_SUPPORT !== undefined
  ? global.TYPED_ARRAY_SUPPORT
  : typedArraySupport()
```
Does not work on browsers that do not support the `global`  the whole lib crashes 

One of such is brave and lately all browsers.

**Comment by feross** [comment]
Buffer expects to be run through the `browserify` build tool which substitutes in a browser shim for `global`.

**Comment by jimmykane** [comment]
Thanks but prefer to add one line `(window as any).global = window;` ;-) Same stuff

**Comment by dmytro-gokun** [comment]
@feross Is that an absolute necessity to require "global"? I mean, it just causes pain for the lib users. If it can be fixed, why not fix it?

**Comment by sixcorners** [comment]
https://github.com/feross/buffer/commit/8746070093390396e497be53e900240c51c2ba49
Am I failing to understand something? Hasn't this reference to global been gone for three years?

**Comment by dmytro-gokun** [comment]
@sixcorners I think, most ppl do not use this lib directly. Instead they use "webpack", which references "node-libs-browser", which in turn references v 4.9.2 of this lib. And that one has this issue.

**Comment by pedrotorchio-frankieone** [comment]
Yeah a bit disappointed, but at least the fix is simple. Thank you
