### ISSUE TITLE
Calling readUInt32LE with no arguments throws an exception in buffer v4

### ISSUE THREAD

**Issue by Borewit** [feross/buffer#237]
Issue on buffer: [4.9.1](https://github.com/feross/buffer/releases/tag/v4.9.1).

**Expected behaviour:**
Call `buffer.readUInt32LE()` will read a 32-bit unsigned integer from the buffer start at position since this is how node.js buffer behaves.

**Actual behaviour:**
Throws an exception: "RangeError: offset is not uint"

There are likely other read function behaving the same. But this specific one, was an issue for me.

Although **this issue is already fixed in v5**, webpack v4 which relying on node-libs-browser, which is relying on buffer 4.9.1 and [does not want to update to v5 for good or bad reasons](https://github.com/webpack/node-libs-browser/pull/68).

Related issues:
1. Borewit/music-metadata-browser#15 (addressed by enforcing buffer v5)
2. Borewit/music-metadata-browser#28 (already addressed, by explicit provided offset)

Do you think it is worth releasing a 4.9 patch @feross?

**Comment by feross** [comment]
It's ridiculous that they won't update to the latest `buffer`. I would rather not support old major versions of packages. It's already so much work to maintain just the latest major version without also fixing old versions. If there's a severe issue affecting you that you can't work around, let me know and I'll consider it in the future. But for now it sounds like you were able to work around the problem, right?

Cheers!
