### ISSUE TITLE
Remove `buffer.inspect`

### ISSUE THREAD

**Issue by feross** [feross/buffer#239]
It has been deprecated, as per @goto-bus-stop's comment here: https://github.com/feross/buffer/pull/204

**Comment by fanatid** [comment]
Any plans about this issue?
- left both methods now
- remove buffer.inspect
- define buffer.inspect only if Symbol `util.inspect.custom` undefined
- something else?

**Comment by goto-bus-stop** [comment]
I mentioned in the PR that the `util` shim would start using the symbol, but I think that didn't actually happen yet as there was another big effort to add `util.types` there and the inspect symbol fell by the wayside. I will work on adding that ASAP. Until then it would be best to keep both around for compatibility reasons.

IMHO `Buffer.prototype.inspect()` isn't really in anyone's way so if I were a `buffer` maintainer i would opt to keep it around for a long time, avoiding a major bump which would have some ecosystem impact, but that's not my decision to make :)

**Comment by feross** [comment]
@goto-bus-stop Thanks for all that context. This package aims for 1-to-1 functionality compatibility with Node.js, so if it's not removed from Node.js LTS yet, then we should keep it here. Thanks for the context.
