### ISSUE TITLE
PhantomJS 2.1.1 (Windows 7.0.0) ERROR: 'This browser lacks typed array (Uint8Array) support which is required by `buffer` v5.x. Use `buffer` v4.x if you require old browser support.'

### ISSUE THREAD

**Issue by JigneshRaval** [feross/buffer#240]
Hi,

I need your help in following issue. 

I am working on Angular project and using PhantomJS 2.1.1 for running test cases. But after last publication of "buffer" package v5.3.0. I am getting error in running test cases. Which breaks the build. 
"buffer" package might be dependency of any internal/child npm package, which is auto updated by build process. So currently we don't have any control on restricting specific version of "buffer".

```
13 08 2019 16:06:22.117:INFO [launcher]: Starting browser PhantomJS
13 08 2019 16:06:29.256:INFO [PhantomJS 2.1.1 (Windows 7.0.0)]: Connected on socket eUBgeUYmmHV90wRvAAAA with id 85706280
PhantomJS 2.1.1 (Windows 7.0.0) ERROR: 'This browser lacks typed array (Uint8Array) support which is required by `buffer` v5.x. Use `buffer` v4.x if you require old browser support.'

PhantomJS 2.1.1 (Windows 7.0.0) ERROR
  TypeError: undefined is not a constructor (evaluating 'Object.setPrototypeOf(Buffer.prototype, Uint8Array.prototype)')
  at C:/Users/A0707515/AppData/Local/Temp/karma-typescript-bundle-163645urT82E2R1Tv.js:143535
```

Can you please guide that how can I fix this issue.

Thanks,
Jignesh

**Comment by vweevers** [comment]
Take into account that PhantomJS was discontinued (March 2018).

**Comment by JigneshRaval** [comment]
Hi @Vincent Weevers,

Thanks for your quick reply.

Can you please suggest any quick solution for this, because our project is bigger and it is divided into multiple installable npm packages. When we ran "npm list buffer", and we found that it is dependency of "Karma-typescript" package. 

```
"karma-typescript": "^3.0.5",
  |--"buffer": "^5.0.6",
```
Your suggestion will help us to manage this project at least until we update all the things to a new version.

Thanks,
Jignesh Raval

**Comment by feross** [comment]
Perhaps you can install `buffer` at the top-level of your project and it will take precedence over the one from `karma-typescript`?

```
npm install buffer@4 --save
```

I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨

**Comment by JigneshRaval** [comment]
Thank you @feross,

Sure, we will try your suggestion.

Thanks again,
