### ISSUE TITLE
On Cordova: Undefined is not a function

### ISSUE THREAD

**Issue by jpcodr** [feross/buffer#241]
I use browserify, that use this library. Recently i updated to the last version and now i cant run my app on android 5.0.0 (API 21)

![Captura de Pantalla 2019-08-26 a la(s) 14 35 04](https://user-images.githubusercontent.com/3935083/63717868-d7f89280-c80e-11e9-9717-d1fc00761a44.png)

`Symbol.for` it's not supported. Can you help me with this?

Thanks in advance.

**Comment by ljharb** [comment]
@feross the fix uses `.for` which is a syntax error in older browsers; I've filed #254 to fix it.
