### ISSUE TITLE
readBigUInt64BE() and similar methods are missing

### ISSUE THREAD

**Issue by nazar-pc** [feross/buffer#244]
Essentially getting this in Browserify build:
> TypeError: Buffer.from(...).readBigUInt64BE is not a function

**Comment by feross** [comment]
According to Node docs this was added in Node 12.0.0 so it makes sense that it's missing from here.

**Comment by nazar-pc** [comment]
Yes, but v12 is out for a while now, so I think it is time to consider implementing new methods.

**Comment by feross** [comment]
I'd love to do it, but I'm very time-constrained at the moment. PR welcome, from you or anyone else!

**Comment by fanatid** [comment]
Node.js internally uses `BigInt` constructor, if this package will start use it... should this methods be available if BigInt is not available in environment?
I'm not familiar too much with bundling systems, can usage of BigInt cause any issues with it?

**Comment by fanatid** [comment]
Just checked how this implemented in node. I think better finish #217 first. @feross are you ok with this?
For reference, PR in node: https://github.com/nodejs/node/pull/19691

**Comment by feross** [comment]
Yep, feel free to tackle this in any order your prefer. Finishing #217 first sounds good. Thanks for all your help, @fanatid.

**Comment by feross** [comment]
Released as 6.0.0
