### ISSUE TITLE
I found a bug about the readUInt32BE.

### ISSUE THREAD

**Issue by DavidLvSinonet** [feross/buffer#252]
~~~javascript
Buffer.prototype.readUInt32BE = function readUInt32BE (offset, noAssert) {
  offset = offset >>> 0
  if (!noAssert) checkOffset(offset, 4, this.length)

  return (this[offset] * 0x1000000) +
    ((this[offset + 1] << 16) |
    (this[offset + 2] << 8) |
    this[offset + 3])
}
~~~
In some Android browser (Chrome 71), it returns a negative number. 
I think it should be add a check.
~~~javascript
  return (this[offset] * 0x1000000) +
    ((this[offset + 1] << 16) |
    (this[offset + 2] << 8) |
    this[offset + 3]) >>> 0
~~~

`readUInt32LE` also need add this >>> 0

**Comment by fanatid** [comment]
Can you check that it's not possible set negative number (or number more than 255) in Uint8Array in described environment?

**Comment by DavidLvSinonet** [comment]
The buffer data is [172, 68, 0 , 0 ]

It uses for mp4a sampleRate.  it returns -1404829696.

**Comment by feross** [comment]
Do you have a minimal example that demonstrates this issue in action? It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.
