### ISSUE TITLE
Text in unit test is being flagged as malicious by corporate security software.

### ISSUE THREAD

**Issue by raven1152** [feross/buffer#255]
This is probably a low priority, but would be a quick fix.  Two unit test files, 

test/node/test-buffer-indexof.js 
test/node/test-buffer-indexof.js, 

use the text "arglebargleglopglyf" to test search functionality.  Recent changes to our corporate security systems have caused these files to be flagged as malicious.

https://github.com/wireghoul/htshells/blob/master/dos/apache.dos.htaccess

I don't know if other users will be affected by this, but currently it causes our automated builds to fail, when our firewall blocks the transfer of these files to/from our build servers.  I understand that the security issue described at wireghoul/htshells does not apply in the context of how you are using the string, but our security software is not sophisticated enough to differentiate.

The problem could be fixed by using a different string to test with.

I don't know the name of our security software, but I can reach out to our security team to get that information if you need it.

**Comment by rotemreiss** [comment]
Hi guys,

Any chance to replace this string to something else to refrain from this F/P detection on some FWs?

Thanks.

**Comment by feross** [comment]
I'm sorry that you're facing this issue. This test file comes directly from the Node.js source code and we sync our tests from them periodically. So the right place to get this fixed is directly in the Node.js project.

Cheers.
