### ISSUE TITLE
.subarray method should return `Buffer` instance

### ISSUE THREAD

**Issue by mikeal** [feross/buffer#260]
Ran across this one today.

`Buffer.subarray()` in Node.js will return a `Buffer` instance, but in the browser it returns a `Uint8Array`.

**Comment by feross** [comment]
I wasn't able to reproduce the issue in Chrome, Brave, Firefox, or Safari on desktop. Which browser did you use?

I tested by browserifying and running:

```
const Buffer = require('./').Buffer
const a = Buffer.from('test')
console.log(a.subarray(2, 3).constructor.name)
```

which prints out `Buffer`.

**Comment by mikeal** [comment]
I’m using polendina for testing, which is a headless chrome that uses webpack (not browserify). I’m also importing the module explicitly rather that relying on globals.

**Comment by feross** [comment]
There's some weirdness going on with the `Symbol.species` code:

https://github.com/feross/buffer/blob/b0a6de5f2131c3e339f14801bb342d16d580ac5f/index.js#L111-L120

Need to investigate further.

**Comment by feross** [comment]
@mikeal Can you try the fix in this PR? https://github.com/feross/buffer/pull/263
