### ISSUE TITLE
Buffer.concat failed when provided totalLength is smaller than sum of buffers size.

### ISSUE THREAD

**Issue by jkkang-kosac** [feross/buffer#272]
5.7 version has bug in Buffer.concat
It raises RangeError when provided totalLength is smaller than sum of buffers size.

5.6 version is okay.
you can test it with this source.

var Buffer = require('buffer/').Buffer;

const a = new Uint8Array(32);
a.fill(0);
const b = new Uint8Array(64);
b.fill(1);

const c = Buffer.concat([a, b], 64);
console.log('c = ', c);

**Comment by davidmurdoch** [comment]
It appears this change is what broke things:

https://github.com/feross/buffer/compare/v5.6.2...v5.7.0#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R414-R418

**Comment by feross** [comment]
PR welcome to address this issue

**Comment by vtn-dev2016** [comment]
Please check package safe-buffer too. I think has same problem

**Comment by feross** [comment]
Fixed by https://github.com/feross/buffer/pull/273

**Comment by feross** [comment]
Released as 5.7.1 and 6.0.1.
