### ISSUE TITLE
Buffer.from('...','hex') does not work

### ISSUE THREAD

**Issue by aavelyn** [feross/buffer#275]
When running the Buffer.from static method in node js on a public key I get different console.log when running it from the browser (in an angular project). It seems that in browser I'm getting decimal instead of 'hex'.

nodejs
```
const pubKey='30819F300D06092A864886F70D010101050003818D0030818902818100B2E9AFAFEED76A5C31D069F84328D785DFE6C40A69F51B29C7D7C91EF171A5EF6AD9FC30AF31F4B59C0FE317E47B5DBAA04E3753AC7F8B0E54D8EB4372894900DE247FD11B8C2208FE1C837ADEC409B0F2EE89A5C54B8AB80D5934FC65100406077D129DC5EB961E883B937C4251FDA4BD77224D1CDEF09151894F902758AA3B0203010001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000';

const buff = Buffer.from(pubKey, 'hex');

console.log(buff)
<Buffer 30 81 9f 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 81 8d 00 30 81 89 02 81 81 00 b2 e9 af af ee d7 6a 5c 31 d0 69 f8 43 28 d7 85 df e6 c4 0a 69 ... 244 more bytes>
```

In angular I have installed `npm i buffer` and provided it in the `pollyfills.ts` like this

```
(window as any).global = window;
(window as any).global.Buffer = require('buffer').Buffer;
(window as any).process = {};

```

Running the same code on the browser [Stackblitz](https://stackblitz.com/edit/angular-ivy-upkebp) yields

![image](https://user-images.githubusercontent.com/16038088/99361200-051cdf00-28b2-11eb-9947-c47a3756565d.png)

So my questions is

Why does the Buffer in the browser return something different? `[0] = 48 vs [0]= 30`

In the Stackblitz example you can see that I'm using the buffer with node-rsa for encyrption. The encrypted value from the nodesjs script works while the one from the browser doesnt.  

[1]: https://i.stack.imgur.com/rU81U.png

Post on Stackoverflow

https://stackoverflow.com/questions/64871119/buffer-library-in-browser-does-not-return-the-same-value-as-in-nodejs?noredirect=1#comment114692330_64871119

**Comment by feross** [comment]
I just tested and both this library (latest version) and Node.js (12 LTS) return the same Buffer object, with `30` as the first byte. I think you're somehow including an older version of `buffer`. This is not a bug in `buffer`.

```js
const assert = require('assert')
const B = require('buffer/').Buffer
const pubKey='30819F300D06092A864886F70D010101050003818D0030818902818100B2E9AFAFEED76A5C31D069F84328D785DFE6C40A69F51B29C7D7C91EF171A5EF6AD9FC30AF31F4B59C0FE317E47B5DBAA04E3753AC7F8B0E54D8EB4372894900DE247FD11B8C2208FE1C837ADEC409B0F2EE89A5C54B8AB80D5934FC65100406077D129DC5EB961E883B937C4251FDA4BD77224D1CDEF09151894F902758AA3B0203010001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
assert.deepEqual(Buffer.from(pubKey, 'hex'), B.from(pubKey, 'hex'))
```

**Comment by aavelyn** [comment]
Hi I could verify your result when running both in nodejs. But I'm getting a different result when running buffer in the browser.

**Comment by feross** [comment]
@aavelyn Please ensure that you're using the latest version of `buffer` in your browser. If your bundler is including `buffer` automatically it may not be using the latest version.

**Comment by aavelyn** [comment]
I found the reason. It is because the browser logs the values in int while nodejs logs it in hex....
Thanks for the support!
