### ISSUE TITLE
readBigUInt64LE is not a function

### ISSUE THREAD

**Issue by sontuphan** [feross/buffer#279]
In native Buffer, it actually has `readBigUInt64LE`. References: https://nodejs.org/docs/latest-v12.x/api/buffer.html#buffer_buf_readbiguint64le_offset.
However, I cannot find the corresponding function in `buffer`. Can some one point me how to solve it?

**Comment by chronark** [comment]
Same here for the `writeBigInt...` methods, I'd be happy to create a PR if I knew where to start.

**Comment by chronark** [comment]
Actually we are just not using it properly :D

It works just fine.
```javasctipt
const Buffer = require("buffer/").Buffer

new Buffer.alloc(20).readBigUInt64LE() // -> 0n
```
