### ISSUE TITLE
Error while using Buffer.from() with a SharedArrayBuffer. 

### ISSUE THREAD

**Issue by wellington-oj** [feross/buffer#283]
Hello.

While using the library to run the node.js version of the Fasta benchmark from [The Computer Language Benchmark Game] (https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/fasta-node-5.html) on the Google Chrome (version 87.0.4280.88) I found an error in the following function:

```
function processResults() {
        while (results.has(lastResult)) {
        const worker = results.get(lastResult);
        const {output, len} = workers.get(worker);
        results.delete(lastResult);

        out.writeBuffer(Buffer.from(output), 0, len);
        nextChunk(worker);
        lastResult++;
        }
}
```

more specifically, on the execution of `out.writeBuffer(Buffer.from(output), 0, len);`
The error message was `The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object`

On my machine, the code runs perfectly on node.js (version 14.13.1). As a very ad hoc solution, I added a specific case for `SharedArrayBuffer` on the `Buffer.from()` function and the aforementioned error got fixed. 
It doesn't seem like a definity solution so I'm opening an issue instead of sending a pull request. 

Cheers.

**Comment by mischnic** [comment]
This should have been fixed by https://github.com/feross/buffer/pull/259

**Comment by feross** [comment]
This is fixed in the current version of `buffer`.  Please make sure that you are using the latest version. `webpack` or `browserify` may be including an older version.
