### ISSUE TITLE
subarray is not re-defined in index.d.ts

### ISSUE THREAD

**Issue by BTOdell** [feross/buffer#297]
The `subarray` function should return a `Buffer`, but currently the types are inheriting the definition from `Uint8Array` which has the function returning a `Uint8Array`.
I believe PR #261 fixed this issue at runtime, but the types were never updated.

**Comment by cmdcolin** [comment]
ill just note buffer@4.9.2 (used by create-react-app@4 with webpack@4) returns a UInt8Array for subarray
