### ISSUE TITLE
Investigate proper `instanceof Buffer` support

### ISSUE THREAD

**Issue by feross** [feross/buffer#40]
I saw a potential way to get `instanceof Buffer` working in a module by @dcodeIO: https://github.com/dcodeIO/node-BufferView/blob/master/BufferView.js

```js
    // Extend DataView and clear all instance methods to be sure
    BufferView.prototype = Object.create(DataView.prototype);
    (function() { for (var i in BufferView.prototype) delete BufferView.prototype[i]; })();
```

**Comment by feross** [comment]
New possible solution: https://github.com/iojs/io.js/issues/106#issuecomment-76251254

**Comment by feross** [comment]
`instanceof Buffer` works correctly in buffer v3.5.0 now!

This fixes the last remaining incompatibility with the node Buffer! And since Buffer in node v4.0.0 is based on `Uint8Array` as well, we're on exactly the same page now!

There's a 50% performance hit on the 16 byte buffer test (`new Buffer(16)`) in non-V8 engines (much better than my previous experiments to get this working). For the 16KB large buffer test (`new Buffer(1600)`), the hit is only 25%, since the difference is drowned out by the zeroing out operation. I expect this to get better over time since subclassing arrays is supported by ES6 now. :+1:

**Comment by dcousens** [comment]
@feross any reason why `node 4.0.0` couldn't be using the same `Buffer` code as this library? (hell, why not the same library).

**Comment by feross** [comment]
Well, they do a bunch of calls directly into the C++ engine. I think one reason they do that is so they can disable the behavior where new typed array memory must be zeroed-out for security reasons in the browser environment. In node, they can do without that and get perf improvements.

Maybe there are more reasons...
