### ISSUE TITLE
Bad name of variable

### ISSUE THREAD

**Issue by BogdanovAnton** [feross/buffer#56]
In this place:

347: var byte = parseInt(string.substr(i * 2, 2), 16)
348: if (isNaN(byte)) throw new Error('Invalid hex string')
349: buf[offset + i] = byte

https://github.com/feross/buffer/blob/3a22a49dad272004455e90c1df3b0ffb5a07f47f/index.js#L347-L349

used variable with name "byte", but such names are only allowed in ecmascript 5. I'm use RhinoScriptEngine in java and Rhino not complete support ecmascript 5 now. 
Please change the code for this example:

347: var byte2 = parseInt(string.substr(i * 2, 2), 16)
348: if (isNaN(byte2)) throw new Error('Invalid hex string')
349: buf[offset + i] = byte2

Thank you.

**Comment by dcousens** [comment]
@BogdanovAnton could probably have made a PR along with this.  In any case #57.

**Comment by feross** [comment]
This will be released as 3.0.4.
