### ISSUE TITLE
Pull in iojs changes / perf improvements

### ISSUE THREAD

**Issue by feross** [feross/buffer#58]
History: https://github.com/iojs/io.js/commits/v1.x/lib/buffer.js

**Comment by feross** [comment]
I just merged all the latest buffer changes from io.js. Almost all the changes were related to performance.

Released as 3.2.0.

**Comment by feross** [comment]
Pretty nice performance improvement to the `Buffer` constructor. :+1: 

Before:
BrowserBuffer#new(16) x 863,493 ops/sec ±1.61% (93 runs sampled)

After:
BrowserBuffer#new(16) x 1,249,470 ops/sec ±0.96% (89 runs sampled)

**Comment by dcousens** [comment]
Cheers for writing this up :)
