### ISSUE TITLE
"call stack size exceeded" for large binary strings in 3.4.2

### ISSUE THREAD

**Issue by nolanlawson** [feross/buffer#69]
In PouchDB we use large binary strings when we store binary data in `localstorage-down` and `level-js`, and our tests started failing recently due to buffer 3.4.1 and 3.4.2 (https://github.com/pouchdb/pouchdb/issues/4164, see discussion over there). In short, 3.4.1 had a perf regression which appears fixed in 3.4.2, but 3.4.2 now has a "call stack size exceeded" error when I test in Chrome 44 (on an admittedly slow laptop, so it may be hard to reproduce on a faster one).

Glancing at the code, I think a reasonable fix would be to break up the array into decent-size chunks and then concat the string together, but I admit I'm not super familiar with the codebase.

**Comment by jessetane** [comment]
Ah, yes the `apply` argument count limit... Chrome seems to bail for > 65535. I had originally written this calling `String.fromCharCode` for each code point but that was rather slow, so @nolanlawson I think your idea to break up the array into chunks at the end seems maybe best.

**Comment by dcousens** [comment]
Resolved in #70

**Comment by adametry** [comment]
Unfortunately, there's not a fixed max arguments (i.e., 0x10000 in Chrome) as the size/complexity of the call stack also influences this threshold. I receive the "call stack size exceeded" while converting moderately large buffers to strings before (@3.4.2) and after the c5a9012 commit. I've wrestled with this issue before and found it best to either use a much smaller chunk size (e.g., 0xfff) or avoid chunked applies entirely. Though, I have no doubt that there are more brilliant solutions. 

To better understand the what is happening, here are two helpful SO explanations:
• [“RangeError: Maximum call stack size exceeded” Why?](http://stackoverflow.com/a/22123980)
• [Chrome: How to solve “Maximum call stack size exceeded” errors on Math.max.apply( Math, array )](http://stackoverflow.com/a/20940386)

**Comment by nolanlawson** [comment]
@adametry Can you open a new issue then? I think using a smaller chunk size is probably a fine solution. I'd suggest a try/catch, but that would lead to deoptimizations, so probably worse.

**Comment by feross** [comment]
We should try making the max argument length smaller - say cut it in half. If that doesn't work, we should probably stop using the `apply` approach.

**Comment by dcousens** [comment]
@feross agreed,  want me to make the change?

**Comment by jessetane** [comment]
Calling `String.fromCharCode` directly should just not be so slow... and in fact, it isn't slow as long as the code points you're handing it are in the ascii range. As soon as you get outside ascii (even if you're still in the BMP!) it seems to slow way down unless you use the `apply` trick.

I guess dropping the `apply` approach entirely makes sense since the failure case is  non-deterministic? Even if we do drop it, we should still be a good deal faster at decoding utf8 than before.

**Comment by nolanlawson** [comment]
I figured this was worth a JSPerf, so I put together a comparison of for loops vs `apply` using a very large array, with [a non-ASCII version of the test](http://jsperf.com/string-fromcharcode-apply-vs-string-fromcharcode-using-/3) and [an ASCII version](http://jsperf.com/string-fromcharcode-apply-vs-string-fromcharcode-using-/5).

I wasn't able to test in Safari or IE (because I'm on Linux), so please test those browsers if you get a chance. Anyway it seems that for non-ASCII, `apply` is ~10x faster on both Chrome and Firefox, and for ASCII the only difference is that on Firefox it's ~2x faster instead of ~10x.

I'm not sure at what point we would be getting diminishing returns for the `apply` trick (my test assumes chunks of 0x10000), but I think it's worth JSPerfing before making a decision.

**Comment by jessetane** [comment]
ah I was testing with smaller strings, like 16 chars. The difference for ascii is less extreme, but apply is probably still worth it:

http://jsperf.com/string-fromcharcode-apply-vs-string-fromcharcode-using-/6

I ran this and the other tests in canary, safari 8, and edge, so their stats should show up for you now - also jsperf doesn't seem to recognize edge yet, so it's getting reported as chrome 42.

**Comment by jessetane** [comment]
jsperf overwrote my last test, so /6 now shows the long string, but with chunk size lowered to 0xFFF, still seems fast.

**Comment by feross** [comment]
Nice to hear that it's still fast with a smaller chunk size. Let's try that.

@dcousens Can you make the change?

**Comment by dcousens** [comment]
@feross done.

**Comment by feross** [comment]
Since this commit (https://github.com/feross/buffer/commit/4ca70711a3c2ff0bbe42be3de91116d784d1fd50) by @dcousens IE8 and iOS 5.1 support is broken. I want to do a release, but can't until this is fixed.

**Comment by nolanlawson** [comment]
Sorry about that. :( What's the error the browser is throwing?

**Comment by feross** [comment]
I didn't see an error in zuul, so we'll need to fire up a VM. My primary laptop broke and I'm borrowing a friend's for the next few weeks since I'm in Europe so I don't have a VM handy.

**Comment by dcousens** [comment]
@feross was it only that commit that was broken? Or all since too?

**Comment by esthrim** [comment]
hi, i know this issue already closed, but i'm  still having this issue using the latest commit. the error happened when saving the buffer to a file using nodejs fs. here is my code

      var fs = require('fs');
      var B = require('buffer/').Buffer;
      var buffin = fs.readFileSync('calibri.ttf');

      var b64 = buffin.toString('base64');

      var bf = new B(b64,'base64');

      fs.writeFile('calibro.ttf', bf, function (err) {
      if (err) throw err;
           console.log('It\'s saved!');
      });

here is my error.

     D:\Project\testbuffer\node_modules\buffer\index.js:703
       return String.fromCharCode.apply(String, res)
                             ^
       RangeError: Maximum call stack size exceeded
         at utf8Slice (D:\Project\testbuffer\node_modules\buffer\index.js:703:30)
        at Buffer.toString (D:\Project\testbuffer\node_modules\buffer\index.js:412:3
     8)
         at fs.js:1079:63
         at FSReqWrap.oncomplete (fs.js:95:15)

is this error still related with the topic ?,
if isn't then i will open another issue .. thanks.

**Comment by jessetane** [comment]
possible fix for the tests: #75
