### ISSUE TITLE
Corrupted file result when saved to file from base64 source

### ISSUE THREAD

**Issue by esthrim** [feross/buffer#74]
my code is like this : 

      var fs = require('fs');
      var B = require('buffer/').Buffer;

      var buffin = fs.readFileSync('excel.xls');

      var b64 = buffin.toString('base64');

      var bf = new B(b64,'base64');

      fs.writeFile('excelo.xls', bf, function (err) {
               if (err) throw err;
                   console.log('It\'s saved!');
      });

the excelo.xls file is cannot be open, because corrupted file.
the filesize is also different with the original file.
the original file is 1,182 kb but the result file is 1,416 kb.

kindly help, thanks.

**Comment by dcousens** [comment]
@esthrim if you could provide the data for us to test this,  that'd be very helpful.

**Comment by esthrim** [comment]
@dcousens  it is only regular excel file containing tabular data. you can also try yourself using simple excel file (xls or xlsx).  or you can use mine (please rename the file to excel.xls) thanks.
![excel](https://cloud.githubusercontent.com/assets/2139726/9423342/2c0d238e-48ea-11e5-9926-61206a3c06a9.png)

**Comment by esthrim** [comment]
sorry i accidentally close the issue

**Comment by esthrim** [comment]
you can also use this file, please rename to .pdf
![test](https://cloud.githubusercontent.com/assets/2139726/9423446/f7f48c82-48ed-11e5-8b53-bdeb20ee7910.png)

**Comment by feross** [comment]
The node API `fs.writeFile` accepts Buffer arguments only. If you pass it a browser buffer (which is really a Uint8Array, it calls `.toString()` on the parameter before writing it.

```js
fs.writeFileSync('test.txt', new Uint8Array([66, 67, 68]))
```

```bash
> cat test.txt
[object Uint8Array]
```

**Comment by dcousens** [comment]
@feross are you sure?  That doesn't line up with his result:

> the original file is 1,182 kb but the result file is 1,416 kb.

**Comment by feross** [comment]
He could be on a different version of node. Node buffers changed significantly in node 0.12 and again in iojs 3.0. In any case, I don't expect this to work.

@esthrim What's the use case for using this module in node?

**Comment by esthrim** [comment]
@feross  actually i just want to test the Buffer's result whether it is the same with the Node's Buffer or not when saving it to a file, and based on your explanation that means that i cannot use the node's writefile function if i want to save the "Feross Buffer" to a file, because the writefile function requires the Node's Buffer type and "Feross Buffer" type is Browser Buffer which is different. if it so then it's my mistake :) thanks anyway.

**Comment by feross** [comment]
@esthrim You can compare feross/buffer to the node buffer by changing your code like this:

```js
  var fs = require('fs');
  var B = require('buffer/').Buffer;

  var buffin = fs.readFileSync('excel.xls');

  var b64 = buffin.toString('base64');

  var bf = new B(b64, 'base64');
  var bf2 = new Buffer(bf);

  fs.writeFile('excelo.xls', bf2, function (err) {
           if (err) throw err;
               console.log('It\'s saved!');
  });
```

Let me know if that works for you.

**Comment by feross** [comment]
@esthrim Also, can you share the version of node you're using?

```
node -v
```
