### ISSUE TITLE
How to use buffer without browserify?

### ISSUE THREAD

**Issue by ajenkul** [feross/buffer#77]
I'm working on a cordova project which is client-side javascript. I want to use buffer to decompress my string like this:
```javascript
var s = Buffer('737AB86B719E82CBC3DDDDC9190ABE0F77CFCE54303230300200', 'hex').toString('binary');
```
Please help me to use your library in client javascript. Thanks you!

**Comment by feross** [comment]
A standalone bundle is available [here](https://wzrd.in/standalone/buffer), for non-browserify users.

**Comment by ajenkul** [comment]
I know it and downloaded it. But how to use your library like that line of code? I just require it by <script> tag

**Comment by feross** [comment]
Yeah, put it in a script tag. It's a standalone browserify bundle that puts itself on the `window` with the name `buffer`, so you don't use the `require` function.

Instead just do this:

```
var Buffer = buffer.Buffer
```

Now you can use `Buffer`.

**Comment by ajenkul** [comment]
Many thanks for you. I did it.
