### ISSUE TITLE
Buffer.concat fails for lists with only one item in it

### ISSUE THREAD

**Issue by SAGV** [feross/buffer#78]
I recently tried to use [telegram.link](https://github.com/enricostara/telegram.link/) library with browsefiry and noticed that all the requests fail with `Uncaught TypeError: item.copy is not a function (index.js:328)`.

I've tried a few workarounds and found out that if I add:
```
if (list.length === 1) {
  return list[0];
}
```
In `Buffer.concat` function, around line `324`, then all the requests pass fine.

I'm not (yet) pro in binary conversion yet so I'd like to ask a question:
What might be wrong with Buffer object passed to `Buffer.concat` so item.copy fails? You might assume that it doesn't pass Buffer object but actually it does, I've checked.

And will my workaround break something in the future?

I can provide a sample repo as a playground if needed ;-)

I've made the change in [my fork](https://github.com/SAGV/buffer/commit/1e4517f35ec8d1e371a374aac0c9af65ffe99d1e), feel free to check it

**Comment by dcousens** [comment]
> What might be wrong with Buffer object passed to Buffer.concat so item.copy fails? You might assume that it doesn't pass Buffer object but actually it does, I've checked.

> Uncaught TypeError: item.copy is not a function (index.js:328).

One of these statements is true.

**Comment by juliangruber** [comment]
i had a similar problem, in my case the real problem was that i was passing typed arrays into `.concat()`, not buffer instances

**Comment by dcousens** [comment]
@SAGV I'm going to close this as a non-issue.  If you have a test-case, feel free to re-open.
