### ISSUE TITLE
Android 4.x support? 

### ISSUE THREAD

**Issue by calvinmetcalf** [feross/buffer#80]
I'm looking into a bug (crypto-browserify/createHash#8)  effecting creating hashes in Android 4.3.1 and earlier.  Some preliminary sauce lab's testing suggests it might effect ciphers too (though could have the same root cause in the hashes if it doesn't effect createCipheriv), that being said it *could* be a bug in buffer and I noticed that this repo doesn't test against android older than 5.0 and since I couldn't find any mention of it in the issues I thought I'd check to make sure there arn't any known issues.

**Comment by nolanlawson** [comment]
Probably worth just opening a pull request to add Android 4.3 tests and see if anything breaks.

**Comment by calvinmetcalf** [comment]
opened #81 but the saucelab tests are not run against pull requests

**Comment by calvinmetcalf** [comment]
ah but I can run them locally

**Comment by calvinmetcalf** [comment]
and they all pass wtf?

**Comment by calvinmetcalf** [comment]
ok found a test that fails on android 4.3

**Comment by dcousens** [comment]
@calvinmetcalf care to share? :)

**Comment by calvinmetcalf** [comment]
yes is the answer
