### ISSUE TITLE
Slicing buffers fails in latest Microsoft Edge

### ISSUE THREAD

**Issue by oskbor** [feross/buffer#86]
slicing buffers fails in Edge 25.10586.0.0
it boils down to this:
```
var buf = new Buffer(100);
var arr = new Uint8Array(100);
buf instanceof Uint8Array; // true
Uint8Array.prototype.subarray.call(arr, 0, 0).length; // 0
Uint8Array.prototype.subarray.call(buf, 0, 0).length; // 100 ! 
```
Would you say this is an issue with Edge or with this lib?

**Comment by nolanlawson** [comment]
This sounds like an issue with Edge, especially if it's a regression from IE11. Should probably be filed on http://connect.microsoft.com/

**Comment by feross** [comment]
This sounds like a regression in Edge from IE11. Can you file a bug report with Microsoft and post the link here?

**Comment by feross** [comment]
Just added Edge to the test suite (https://github.com/feross/buffer/pull/87) and for what it's worth, the tests all pass.

**Comment by oskbor** [comment]
I have tested it some more all tests pass in Edge, as you said. 
When i use Buffer from https://wzrd.in/standalone/buffer, I don't get these issues.
So it seems to be something in our tool chain that is causing this issue. Maybe some combination of Babel/browserify. I will continue down the rabbit hole, thanks for your assistance and for updating your tests to run on Edge

**Comment by feross** [comment]
Thanks for updating this issue, @oskbor. If you end up discovering a bug, please do open a new issue, or comment in this one. Cheers!

**Comment by oskbor** [comment]
Bug report posted to Microsoft
https://connect.microsoft.com/IE/feedbackdetail/view/2207846/buffer-uint8array-regression-in-latest-edge

**Comment by feross** [comment]
I just marked that I've also experienced the bug on the issue.

**Comment by oskbor** [comment]
Thanks!
Do you have any ideas on why my build might fail while the one on wzrd.in does not? I spent all day trying to find the reason, but ended up no wiser :confused:

**Comment by feross** [comment]
@oskbor Can you open a new issue?

**Comment by Sjors** [comment]
The test sweet uses Edge 13 which is ancient. This bug doesn't occur in Edge 20. It does in Edge 25. There are no VM's out there running Edge 25 as far as I know; I spent a ton of time getting my hands on a physical machine to reproduce this :-)

**Comment by feross** [comment]
@Sjors EdgeHTML13 is actually pretty new. See: https://en.wikipedia.org/wiki/Microsoft_Edge#Release_history And there's no way to get a newer version with Sauce Labs right now.

To be clear, you're not reporting a new issue. Just saying that you got this bug using an old version of browserify/buffer?

**Comment by Sjors** [comment]
I see, good to know EdgeHTML has different versioning from the browser.
>
>
The issue went away for me as soon as I upgraded browserify*, so indeed I'm
not reporting a new bug.

* = make sure grunt-browserify is also up to date and using browserify >=13
