### ISSUE TITLE
Remove buffer.toArrayBuffer()

### ISSUE THREAD

**Issue by feross** [feross/buffer#90]
Node removed the buffer.toArrayBuffer() API sometime during node 0.11. Users who rely on it will have code that doesn't work in node.js, which is unfortunate.

Let's remove buffer.toArrayBuffer() so we have parity with node.js.

**Comment by RaulTsc** [comment]
Hey, I'd like to take a stab at this if that's fine :). Will follow up tomorrow or the day after that

**Comment by feross** [comment]
Should be just a simple change to delete the method. If you want to send a PR, that's fine :+1:
